spring.application.name=support-ticket-api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


client-id=support-ticket-api
issuer-uri=http://localhost:9090/realms/support-ticket-api
client-secret=${CLIENT_SECRET}
audience=account
spring.security.oauth2.resourceserver.jwt.issuer-uri=${issuer-uri}
spring.security.oauth2.resourceserver.jwt.audiences=${audience}